export const TOGGLE_PROGRESS = 'TOGGLE_PROGRESS'

export const RECEIVE_COINS = 'ADD_COIN'

export const CHANGE_SORTING_PARAM = 'CHANGE_SORTING_PARAM'

export const SEARCH_BY_STRING = 'SEARCH_BY_STRING'

export const SELECT_CURRENCY = 'SELECT_CURRENCY'

export const EXCHANGE_CURRENCY = 'EXCHANGE_CURRENCY'